import type {
  PortalDataset,
  PortalUser,
  PreviewPersona,
} from "./portal-access";

export const DEMO_PERSONA_USER_IDS: Record<PreviewPersona, string> = {
  investor: "demo-investor",
  applicant: "demo-applicant",
  partner: "demo-partner",
  "firm-admin": "demo-firm-admin",
  "hnc-admin": "demo-hnc-admin",
};

const users: PortalUser[] = [
  {
    id: DEMO_PERSONA_USER_IDS.investor,
    firstName: "Deniz",
    lastName: "Arslan",
    displayName: "Deniz Arslan",
    email: "deniz.arslan@example.com",
    locale: "tr",
    emailVerified: true,
    accountStatus: "active",
    accountIntent: "investor",
    investorAccountType: "individual",
    onboardingStatus: "completed",
    residenceJurisdiction: "Ontario, Canada",
    investmentObjective: "Long-term income and capital growth",
    timeHorizon: "5+ years",
    riskAcknowledgedAt: "2026-07-10T12:00:00.000Z",
    contactConsentAt: "2026-07-10T12:00:00.000Z",
    platformRoles: [],
  },
  {
    id: DEMO_PERSONA_USER_IDS.applicant,
    firstName: "Mert",
    middleNames: "Can",
    lastName: "Yıldız",
    displayName: "Mert Can Yıldız",
    email: "mert.yildiz@example.com",
    locale: "tr",
    emailVerified: true,
    accountStatus: "active",
    accountIntent: "turkiye_licensed_professional_or_firm",
    onboardingStatus: "completed",
    residenceJurisdiction: "Istanbul, Türkiye",
    contactConsentAt: "2026-07-14T12:00:00.000Z",
    platformRoles: [],
  },
  {
    id: DEMO_PERSONA_USER_IDS.partner,
    firstName: "Selin",
    lastName: "Aydın",
    displayName: "Selin Aydın",
    email: "selin.aydin@marmarawealth.example",
    locale: "tr",
    emailVerified: true,
    accountStatus: "active",
    accountIntent: "turkiye_licensed_professional_or_firm",
    onboardingStatus: "completed",
    residenceJurisdiction: "Istanbul, Türkiye",
    contactConsentAt: "2026-01-04T12:00:00.000Z",
    platformRoles: [],
  },
  {
    id: DEMO_PERSONA_USER_IDS["firm-admin"],
    firstName: "Aylin",
    lastName: "Kara",
    displayName: "Aylin Kara",
    email: "aylin.kara@marmarawealth.example",
    locale: "tr",
    emailVerified: true,
    accountStatus: "active",
    platformRoles: [],
  },
  {
    id: DEMO_PERSONA_USER_IDS["hnc-admin"],
    firstName: "Jack",
    lastName: "Hunter",
    displayName: "Jack Hunter",
    email: "jack@jackhunter.com",
    locale: "en",
    emailVerified: true,
    accountStatus: "active",
    platformRoles: ["platform_admin", "compliance_admin", "finance_admin"],
  },
];

export const initialPortalDataset: PortalDataset = {
  users,
  organizations: [
    {
      id: "org-marmara",
      legalName: "Marmara Wealth Partners A.Ş.",
      tradingName: "Marmara Wealth Partners",
      firmType: "Yetkili Yatırım Kuruluşu",
      website: "https://marmarawealth.example",
      businessDomain: "marmarawealth.example",
      spkRegistration: "SPK-YK-2026-0148",
      registeredAddress: "Levent, Şişli, İstanbul, Türkiye",
      authorizedContact: "Aylin Kara",
      complianceContact: "uyum@marmarawealth.example",
      status: "active",
    },
    {
      id: "org-bosphorus",
      legalName: "Bosphorus Capital Menkul Değerler A.Ş.",
      tradingName: "Bosphorus Capital",
      firmType: "Aracı Kurum",
      website: "https://bosphoruscapital.example",
      businessDomain: "bosphoruscapital.example",
      status: "pending",
    },
  ],
  memberships: [
    {
      id: "member-selin",
      organizationId: "org-marmara",
      userId: DEMO_PERSONA_USER_IDS.partner,
      roles: ["representative"],
      status: "active",
      workEmail: "selin.aydin@marmarawealth.example",
      registeredName: "Selin Aydın",
      licenceType: "Sermaye Piyasası Faaliyetleri Düzey 1",
      maskedLicenceNumber: "12••••48",
      verificationStatus: "verified",
      requestedAt: "2026-01-04T15:00:00.000Z",
      approvedAt: "2026-01-08T14:00:00.000Z",
    },
    {
      id: "member-aylin",
      organizationId: "org-marmara",
      userId: DEMO_PERSONA_USER_IDS["firm-admin"],
      roles: ["membership_admin", "finance_admin"],
      status: "active",
      workEmail: "aylin.kara@marmarawealth.example",
      registeredName: "Aylin Kara",
      licenceType: "Sermaye Piyasası Faaliyetleri Düzey 3",
      maskedLicenceNumber: "41••••02",
      verificationStatus: "verified",
      requestedAt: "2025-12-10T15:00:00.000Z",
      approvedAt: "2025-12-18T14:00:00.000Z",
    },
    {
      id: "member-mert",
      organizationId: "org-marmara",
      userId: DEMO_PERSONA_USER_IDS.applicant,
      roles: ["representative"],
      status: "pending",
      workEmail: "mert.yildiz@marmarawealth.example",
      registeredName: "Mert Can Yıldız",
      licenceType: "Sermaye Piyasası Faaliyetleri Düzey 1",
      maskedLicenceNumber: "78••••21",
      verificationStatus: "pending",
      requestedAt: "2026-07-14T15:00:00.000Z",
    },
  ],
  affiliations: [
    {
      id: "affiliation-selin",
      organizationId: "org-marmara",
      userId: DEMO_PERSONA_USER_IDS.partner,
      status: "approved_by_firm",
      primary: true,
      approvedBy: DEMO_PERSONA_USER_IDS["firm-admin"],
      approvedAt: "2026-01-08T14:00:00.000Z",
    },
    {
      id: "affiliation-mert",
      organizationId: "org-marmara",
      userId: DEMO_PERSONA_USER_IDS.applicant,
      status: "pending_firm",
      primary: true,
    },
  ],
  partnerApplications: [
    {
      id: "application-selin",
      userId: DEMO_PERSONA_USER_IDS.partner,
      organizationId: "org-marmara",
      registeredFirstNames: "Selin",
      registryLastName: "AYDIN",
      normalizedRegistryLastName: "AYDIN",
      licenceDocumentNumber: "12345648",
      licenceType: "Sermaye Piyasası Faaliyetleri Düzey 1",
      professionalTitle: "Lisanslı Yatırımcı Temsilcisi",
      firmWorkEmail: "selin.aydin@marmarawealth.example",
      lookupConsent: true,
      accuracyConsent: true,
      status: "approved",
      submittedAt: "2026-01-04T15:00:00.000Z",
      updatedAt: "2026-01-09T14:00:00.000Z",
    },
    {
      id: "application-mert",
      userId: DEMO_PERSONA_USER_IDS.applicant,
      organizationId: "org-marmara",
      registeredFirstNames: "Mert Can",
      registryLastName: "YILDIZ",
      normalizedRegistryLastName: "YILDIZ",
      licenceDocumentNumber: "78901221",
      licenceType: "Sermaye Piyasası Faaliyetleri Düzey 1",
      professionalTitle: "Yatırımcı Temsilcisi",
      firmWorkEmail: "mert.yildiz@marmarawealth.example",
      evidenceFilename: "spl-lisans-belgesi.pdf",
      lookupConsent: true,
      accuracyConsent: true,
      status: "under_review",
      submittedAt: "2026-07-14T15:00:00.000Z",
      updatedAt: "2026-07-15T14:00:00.000Z",
    },
  ],
  licenseVerifications: [
    {
      id: "verification-selin",
      applicationId: "application-selin",
      userId: DEMO_PERSONA_USER_IDS.partner,
      queriedLicenceNumber: "12345648",
      queriedRegistryLastName: "AYDIN",
      sourceUrl: "https://lsts.spl.com.tr/bilgi-sorgulama",
      result: "verified",
      returnedLicenceTypes: ["Sermaye Piyasası Faaliyetleri Düzey 1"],
      returnedStatus: "Aktif",
      renewalInformation: "Yenileme eğitimi güncel",
      reviewerId: DEMO_PERSONA_USER_IDS["hnc-admin"],
      reviewerName: "Jack Hunter",
      reviewerNotes: "Licence and registry surname matched the public SPL result.",
      verifiedAt: "2026-01-09T14:00:00.000Z",
    },
    {
      id: "verification-mert-pending",
      applicationId: "application-mert",
      userId: DEMO_PERSONA_USER_IDS.applicant,
      queriedLicenceNumber: "78901221",
      queriedRegistryLastName: "YILDIZ",
      sourceUrl: "https://lsts.spl.com.tr/bilgi-sorgulama",
      result: "pending",
      returnedLicenceTypes: [],
      verifiedAt: "2026-07-15T14:00:00.000Z",
    },
  ],
  partnerAccounts: [
    {
      id: "partner-selin",
      userId: DEMO_PERSONA_USER_IDS.partner,
      organizationId: "org-marmara",
      status: "active",
      tier: "associate",
      annualClearedCapital: 650_000,
      relationshipSince: "2026-01-09",
    },
  ],
  offeringAccess: [
    {
      id: "access-marmara-lankin",
      organizationId: "org-marmara",
      offeringId: "lankin-apartment-reit",
      status: "on_shelf",
      effectiveAt: "2026-01-12",
    },
    {
      id: "access-marmara-legacy",
      organizationId: "org-marmara",
      offeringId: "legacy-epiphany",
      status: "approved",
      effectiveAt: "2026-02-02",
    },
  ],
  commissions: [
    {
      id: "commission-selin-1",
      beneficiaryType: "representative",
      beneficiaryUserId: DEMO_PERSONA_USER_IDS.partner,
      introducingRepresentativeId: DEMO_PERSONA_USER_IDS.partner,
      referralId: "ref-1042",
      redactedReferralReference: "HNC-REF-1042",
      offeringId: "lankin-apartment-reit",
      grossDistributionCommissionAmount: 10_000,
      allocationPercentage: 30,
      partnerTier: "associate",
      amount: 3_000,
      currency: "CAD",
      earningPeriod: "Q2 2026",
      fundedAt: "2026-07-12",
      distributionCommissionReceivedAt: "2026-07-14",
      description: "Associate fund distribution commission allocation",
      status: "approved",
      approvedAt: "2026-07-15T14:00:00.000Z",
    },
    {
      id: "commission-firm-1",
      beneficiaryType: "organization",
      beneficiaryOrganizationId: "org-marmara",
      introducingRepresentativeId: DEMO_PERSONA_USER_IDS.partner,
      referralId: "ref-1048",
      redactedReferralReference: "HNC-REF-1048",
      offeringId: "legacy-epiphany",
      grossDistributionCommissionAmount: 20_000,
      allocationPercentage: 30,
      partnerTier: "associate",
      amount: 6_000,
      currency: "CAD",
      earningPeriod: "Q2 2026",
      fundedAt: "2026-07-03",
      distributionCommissionReceivedAt: "2026-07-06",
      description: "Associate fund distribution commission allocated to the approved firm",
      status: "paid",
      approvedAt: "2026-07-07T14:00:00.000Z",
      paidAt: "2026-07-10T14:00:00.000Z",
      paymentReference: "HNC-PAY-260710-04",
    },
  ],
  investments: [
    {
      id: "investment-deniz-1",
      userId: DEMO_PERSONA_USER_IDS.investor,
      offeringId: "lankin-apartment-reit",
      amount: 100_000,
      accountType: "individual",
      preferredContactChannel: "email",
      contactConsentAt: "2026-07-10T14:00:00.000Z",
      submittedAt: "2026-07-10T14:00:00.000Z",
      status: "funded",
      updatedAt: "2026-07-15T14:00:00.000Z",
    },
    {
      id: "investment-selin-1",
      userId: DEMO_PERSONA_USER_IDS.partner,
      offeringId: "legacy-epiphany",
      amount: 150_000,
      accountType: "individual",
      preferredContactChannel: "email",
      contactConsentAt: "2026-07-08T14:00:00.000Z",
      submittedAt: "2026-07-08T14:00:00.000Z",
      status: "funded",
      updatedAt: "2026-07-13T14:00:00.000Z",
    },
  ],
  referrals: [],
  qualificationAssessments: [],
  documents: [],
  auditEvents: [
    {
      id: "audit-1",
      actorUserId: DEMO_PERSONA_USER_IDS["firm-admin"],
      action: "firm_affiliation.requested",
      entityType: "firm_affiliation",
      entityId: "affiliation-mert",
      summary: "Marmara Wealth Partners received a request to confirm the applicant's firm association.",
      occurredAt: "2026-07-15T14:00:00.000Z",
    },
    {
      id: "audit-2",
      actorUserId: DEMO_PERSONA_USER_IDS["hnc-admin"],
      action: "license_verification.queued",
      entityType: "partner_application",
      entityId: "application-mert",
      summary: "SPL reviewer-assisted lookup queued.",
      occurredAt: "2026-07-15T14:05:00.000Z",
    },
  ],
};

export function demoUserForPersona(persona: PreviewPersona) {
  return users.find((user) => user.id === DEMO_PERSONA_USER_IDS[persona]) ?? users[0];
}
